using Microsoft.EntityFrameworkCore;
using WebbApp.Models.Entities;

namespace WebbApp.Contexts;

public class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options) : base(options)
    {
    }
    public DbSet<CategoryEntity> Categories { get; set; }
    public DbSet<ProductCategoryEntity> ProductCategories { get; set; }
    public DbSet<TagEntity> Tags { get; set; }
    public DbSet<ProductTagEntity> ProductTags { get; set; }
    public DbSet<ProductEntity> Products { get; set; }
    public DbSet<ProductReviewEntity> ProductReviews { get; set; }
    public DbSet<StockEntity> Stocks { get; set; }
    public DbSet<ShowcaseEntity> Showcases { get; set; }
    public DbSet<CollectionEntity> Collections { get; set; }
    public DbSet<OrderEntity> Orders { get; set; }
    public DbSet<OrderRowEntity> OrderRows { get; set;}

    /*
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ShowcaseEntity>().HasData(new ShowcaseEntity
        {
            Ingress = "WELCOME TO BMERKETO SHOP",
            Title = "Exclusive Chair gold Collection.",
            ImageUrl = "625x647.svg",
            LinkText = "SHOP NOW",
            LinkUrl = "/products"
        });

        modelBuilder.Entity<CategoryEntity>().HasData(
            new CategoryEntity { CategoryName = "bag" },
            new CategoryEntity { CategoryName = "dress" },
            new CategoryEntity { CategoryName = "decoration" },
            new CategoryEntity { CategoryName = "essentials" },
            new CategoryEntity { CategoryName = "interior" },
            new CategoryEntity { CategoryName = "laptops" },
            new CategoryEntity { CategoryName = "mobile" },
            new CategoryEntity { CategoryName = "beauty" },
            new CategoryEntity { CategoryName = "electronics" }
        );

        modelBuilder.Entity<TagEntity>().HasData(
            new TagEntity { TagName = "new" },
            new TagEntity { TagName = "popular" },
            new TagEntity { TagName = "featured" },
            new TagEntity { TagName = "summer sale" },
            new TagEntity { TagName = "outgoing" }
        );

        modelBuilder.Entity<ProductEntity>().HasData(
            new ProductEntity { ArticleNumber = "S1132", ProductName = "Apple watch collection", ImageUrl = "369x310.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today." },
            new ProductEntity { ArticleNumber = "S8812", ProductName = "Apple watch collection", ImageUrl = "369x310.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today." },
            new ProductEntity { ArticleNumber = "25695", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "35685", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "48952", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "52365", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "75214", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "89652", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "96174", ProductName = "Beauty collection", ImageUrl = "270x295.svg", Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you." },
            new ProductEntity { ArticleNumber = "f-25695", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-35685", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-48952", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-52365", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-75214", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-89652", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-96174", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." },
            new ProductEntity { ArticleNumber = "f-06174", ProductName = "Apple watch collection", ImageUrl = "270x295.svg", Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.", Description = "Discover the Apple Watch Collection—a range of smartwatches that blend technology and style flawlessly. From the flagship Series 7 with its advanced features, to the fashion-forward Apple Watch Hermès and the sporty Apple Watch Nike, there's a perfect fit for everyone. Seamlessly integrated with your iPhone, these watches keep you connected, organized, and empowered. With a wide selection of interchangeable bands and customizable features, personalize your Apple Watch to reflect your unique style and personality. Elevate your daily life with the Apple Watch Collection." }            
        );

        modelBuilder.Entity<ProductReviewEntity>().HasData(
            new ProductReviewEntity { ProductArticleNumber = "f-25695", Rating = 4, Comment = "Apple Watch Series 6: \n\"The Apple Watch Series 6 is a game-changer! The blood oxygen level monitoring, ECG feature, and always-on display are amazing. It seamlessly integrates with my iPhone and keeps me connected throughout the day.\" \n - Sarah" },
            new ProductReviewEntity { ProductArticleNumber = "f-35685", Rating = 5, Comment = "Apple Watch SE: \n\"The Apple Watch SE offers excellent value for money. It has all the essential features like fitness tracking, heart rate monitoring, and notifications. The display is vibrant, and the battery life is impressive. Perfect for someone looking to enter the world of smartwatches.\" \n - Mark" },
            new ProductReviewEntity { ProductArticleNumber = "f-52365", Rating = 5, Comment = "Apple Watch Series 5:\n\"I love my Apple Watch Series 5! The always-on display is a game-changer, and the ECG function gives me peace of mind. The build quality and design are top-notch. It's become an indispensable part of my daily routine.\" \n - Emily" },
            new ProductReviewEntity { ProductArticleNumber = "f-75214", Rating = 5, Comment = "Apple Watch Series 4:\n\"The Apple Watch Series 4 is a fantastic smartwatch. The larger display, faster performance, and improved heart rate monitoring are remarkable. It looks stylish, and the battery life easily gets me through the day.\" \n - Jason" },
            new ProductReviewEntity { ProductArticleNumber = "f-89652", Rating = 4, Comment = "Apple Watch Nike Edition:\n\"The Apple Watch Nike Edition is perfect for fitness enthusiasts like me. The exclusive Nike watch faces, breathable bands, and preloaded Nike Run Club app motivate me to achieve my fitness goals. It's a fantastic combination of style and fitness tracking.\" \n - Michelle" },
            new ProductReviewEntity { ProductArticleNumber = "f-96174", Rating = 4, Comment = "The Apple Watch Collection offers an excellent blend of style and functionality. The variety of watch faces and interchangeable bands allow me to customize it to suit my preferences and occasions. The integration with my iPhone is seamless, enabling me to receive notifications, answer calls, and even use Siri directly from my wrist. The watch's performance is snappy, and the display is vibrant and easy to read. However, I would appreciate more third-party app support and improved battery life for longer usage without frequent charging. Overall, the Apple Watch Collection is a solid smartwatch choice for Apple ecosystem users. \n - Jim" },
            new ProductReviewEntity { ProductArticleNumber = "f-06174", Rating = 5, Comment = "The Apple Watch Collection is a game-changer! The sleek design and premium materials make it a stylish accessory that complements any outfit. The functionality is outstanding, with a wide range of features like heart rate monitoring, activity tracking, and notifications. The watch face is customizable, allowing me to personalize it to my liking. The battery life is impressive, lasting me through a full day of use. Overall, I highly recommend the Apple Watch Collection to anyone looking for a versatile and reliable smartwatch.\n - Linn" },
            new ProductReviewEntity { ProductArticleNumber = "f-48952", Rating = 4, Comment = "The Apple Watch Collection is a fantastic fitness companion. The built-in workout tracking features are accurate and comprehensive, helping me monitor my progress and set new fitness goals. The watch's heart rate monitor is incredibly useful during workouts, ensuring that I stay in my target heart rate zone. The GPS functionality allows me to track my outdoor runs accurately. The only downside is that the battery life could be better, especially during extended workouts. Nonetheless, I consider the Apple Watch Collection an essential tool for fitness enthusiasts.\n - Leah" }
        );     

        modelBuilder.Entity<StockEntity>().HasData(
            new StockEntity { ArticleNumber = "f-25695", Price = 30, OnSale = false, Quantity = 0, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-35685", Price = 30, OnSale = false, Quantity = 0, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-52365", Price = 30, OnSale = false, Quantity = 0, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-75214", Price = 30, OnSale = false, Quantity = 25, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-89652", Price = 30, OnSale = false, Quantity = 25, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-96174", Price = 30, OnSale = false, Quantity = 50, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-06174", Price = 30, OnSale = false, Quantity = 50, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "f-48952", Price = 30, OnSale = false, Quantity = 50, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "S1132", Price = 12, OnSale = true, Quantity = 10, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "S8812", Price = 12, OnSale = true, Quantity = 15, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "25695", Price = 30, OnSale = false, Quantity = 125, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "35685", Price = 30, OnSale = false, Quantity = 125, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "48952", Price = 30, OnSale = false, Quantity = 125, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "52365", Price = 30, OnSale = false, Quantity = 105, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "75214", Price = 30, OnSale = false, Quantity = 105, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "89652", Price = 30, OnSale = false, Quantity = 105, StandardCurrency = "USD" },
            new StockEntity { ArticleNumber = "96174", Price = 30, OnSale = false, Quantity = 125, StandardCurrency = "USD" }       
        );
    }*/
}
