// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbApp.Contexts;

#nullable disable

namespace WebbApp.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebbApp.Models.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "all"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "bag"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "dress"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "decoration"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "essentials"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "interior"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "laptops"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "mobile"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "beauty"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "shoes"
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.CollectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CheckOut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.OrderRowEntity", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("money");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductArticleNumber");

                    b.ToTable("OrderRows");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = "B-45678",
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = "B-67898",
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = "SH-99875",
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = "DR-45875",
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = "DR-22896",
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = "DE-52365",
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = "DE-45965",
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = "IN-89652",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "T-44183",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "DE-15963",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "LA-12856",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "IN-85875",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "L-96174",
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = "FE-12345",
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = "FE-23456",
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = "FE-34567",
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = "M-77124",
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = "M-66124",
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = "GC-58966",
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = "BE-75214",
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = "BE-89214",
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = "SH-77124",
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = "SH-89514",
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = "SH-96315",
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = "135685",
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = "356899",
                            CategoryId = 9
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductEntity", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArticleNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ArticleNumber = "135685",
                            ImageUrl = "pexels-beautyColl.jpg",
                            Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you.",
                            ProductName = "Beauty set for summer"
                        },
                        new
                        {
                            ArticleNumber = "356899",
                            ImageUrl = "pexels-beauty.jpg",
                            Ingress = "Discover our exquisite beauty collection, where elegance meets innovation. Unleash your radiance with our curated selection of high-quality products that elevate your skincare and makeup routine. From luxurious serums to captivating cosmetics, each item is designed to enhance your natural beauty. Explore our range and embark on a transformative journey to reveal your inner glow. Indulge in our carefully crafted collection and experience the power of self-care. Shop now and embrace the beauty that lies within you.",
                            ProductName = "Beauty collection"
                        },
                        new
                        {
                            ArticleNumber = "GC-58966",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "pexels-goldchair.jpg",
                            Ingress = "Discover pure elegance with our White Exclusive Chair. Featuring exquisite wooden \"legs\" and a pristine white upholstery, this chair adds a touch of sophistication to any space. Experience unparalleled style and comfort in one stunning piece of furniture.",
                            ProductName = "Exclusive Chair"
                        },
                        new
                        {
                            ArticleNumber = "FE-12345",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "Apple_watch-series-6-blue.jpg",
                            Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.",
                            ProductName = "Apple Watch Series 6 (blue)"
                        },
                        new
                        {
                            ArticleNumber = "FE-23456",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "Apple_watch-series-6.jpg",
                            Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.",
                            ProductName = "Apple Watch Series 6 (white)"
                        },
                        new
                        {
                            ArticleNumber = "FE-34567",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "Apple_watch-series-6-coral.jpg",
                            Ingress = "Discover the Apple Watch Collection – a fusion of innovation and style. Stay connected, track your fitness, stream music, make payments, and more, all from your wrist. Personalize your watch with a variety of bands and enjoy a stunning Retina display. Seamlessly integrated with your iPhone, the Apple Watch Collection is the ultimate accessory for convenience and fashion-forward individuals. Elevate your wrist today.",
                            ProductName = "Apple Watch Series 6 (coral)"
                        },
                        new
                        {
                            ArticleNumber = "B-45678",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "pexels-backpack.jpg",
                            Ingress = "Experience rugged elegance with our Forest-themed Backpack. Combining durability and style, this backpack features earthy tones inspired by the enchanting colors of the woods. Prepare for your outdoor adventures with confidence, as this backpack offers ample storage and ergonomic comfort. Embrace the wilderness in style with our powerful Forest-colored backpack.",
                            ProductName = "Nature's Trail Backpack"
                        },
                        new
                        {
                            ArticleNumber = "B-67898",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "pexels-bluebag.jpg",
                            Ingress = "Unleash your style with our Blue Horizon Backpack. This vibrant and versatile accessory combines sleek aesthetics with ample storage space and ergonomic comfort. Stand out from the crowd with the captivating blue hue, perfect for urban exploration or outdoor adventures. Elevate your everyday carry with the Blue Horizon Backpack and make a bold statement wherever you go.",
                            ProductName = "Skyline Explorer Backpack"
                        },
                        new
                        {
                            ArticleNumber = "DE-52365",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "pexels-balloons.jpg",
                            Ingress = "Experience the vibrant fusion of colors with our Yellow and Black Balloon Decorations. These captivating decorations effortlessly add a pop of energy and style to your event. Whether it's a birthday, wedding, or festive celebration, the dynamic combination of yellow and black creates an atmosphere of excitement and elegance. Crafted to impress, our high-quality balloons are designed to make a lasting impact. Elevate your decor with the lively charm of our Yellow and Black Balloon Decorations and let the festivities begin.",
                            ProductName = "Yellow and Black Balloon Decorations"
                        },
                        new
                        {
                            ArticleNumber = "DE-45965",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.\n\nSed efficitur lobortis luctus. Quisque non purus justo. Nunc convallis hendrerit elit, id cursus lacus laoreet ut. Fusce tempus libero eu dui interdum, a posuere velit congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam at mi lorem. Suspendisse varius nulla quis ligula tristique, in aliquet mauris interdum. Curabitur eget metus id ex euismod pellentesque. Fusce ut finibus nunc.",
                            ImageUrl = "pexels-decostar.jpg",
                            Ingress = "Elevate your space with the ethereal beauty of our Blue, Gray, and White Paper Stars. These exquisite decorations effortlessly infuse a sense of celestial elegance into any setting. Hang them, dangle them, or scatter them for a mesmerizing effect. With their delicate craftsmanship and a palette of soothing blue, elegant gray, and pristine white tones, these paper stars create a serene and captivating atmosphere. Let your imagination take flight as you adorn your surroundings with the Stellar Elegance of our Blue, Gray, and White Paper Stars.",
                            ProductName = "Blue/Gray/White Paper Stars"
                        },
                        new
                        {
                            ArticleNumber = "BE-75214",
                            ImageUrl = "pexels-diamondheels.jpg",
                            Ingress = "Elevate your style to new heights with our White Strass Small High Heels. Designed for weddings and special events, these heels exude a glamorous charm. The dazzling strass embellishments add a touch of sparkle and elegance, while the small heel offers both comfort and sophistication. Step into a world of blissful elegance and make a statement at your special occasion with our glamorous White Strass Small High Heels.",
                            ProductName = "White Strass Small High Heels"
                        },
                        new
                        {
                            ArticleNumber = "BE-89214",
                            ImageUrl = "pexels-greenheels.jpg",
                            Ingress = " Step into a world of refined beauty with our Verdant Elegance: Green Small High Heels. These captivating heels in a stunning green shade are perfect for adding a touch of sophistication to your wedding or special event attire. The sleek and stylish design complements a variety of outfits, while the small heel offers both comfort and grace. Elevate your look with the natural allure of our Green Small High Heels and make a statement of elegant charm.",
                            ProductName = "Green Small High Heels"
                        },
                        new
                        {
                            ArticleNumber = "IN-89652",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-interior.jpg",
                            Ingress = "Transform your space with our Hexagonal Shelves Trio in Forest Green, Gray, and White. These three stylish shelves offer a modern and versatile storage solution for your interior. With their unique hexagonal design and varying sizes, they create an eye-catching display for your favorite items. The forest green, gray, and white colors add a touch of sophistication and complement any decor style. Enhance your organization and aesthetic appeal with our Hexagonal Shelves Trio, a perfect addition to elevate your interior space.",
                            ProductName = "Trio of Hexagonal Shelves"
                        },
                        new
                        {
                            ArticleNumber = "L-96174",
                            ImageUrl = "pexels-laptop.jpg",
                            Ingress = "Unleash the power of productivity with the ThinkPad Lenovo laptop. Engineered for performance and reliability, this sleek device is designed to elevate your computing experience. With its cutting-edge features and robust build quality, the ThinkPad Lenovo delivers exceptional speed, efficiency, and durability. Whether you're tackling demanding work tasks or enjoying multimedia entertainment, this laptop is your ultimate companion. Experience the perfect blend of power and performance with the ThinkPad Lenovo and stay ahead of the game.",
                            ProductName = "Laptop Thinkpad Lenovo"
                        },
                        new
                        {
                            ArticleNumber = "M-77124",
                            ImageUrl = "pexels-whiteappleserie.jpg",
                            Ingress = "Experience the epitome of seamless connectivity with Apple Mobile & Watch. These cutting-edge devices combine innovation and style to keep you effortlessly connected throughout your day. The Apple Mobile offers a sleek and intuitive interface, while the Apple Watch provides convenience and functionality right on your wrist. Stay connected, track your fitness, and enjoy the best of Apple's innovation with this dynamic duo. Elevate your digital lifestyle with Apple Mobile & Watch and discover a new level of connected innovation.",
                            ProductName = "Apple Mobile & Watch: Connected Innovation"
                        },
                        new
                        {
                            ArticleNumber = "M-66124",
                            ImageUrl = "pexels-samsung.jpg",
                            Ingress = "Experience the future with the Samsung S22. This innovative smartphone combines advanced features, powerful performance, and a sleek design that's bound to impress. With its immersive display, lightning-fast speed, and cutting-edge camera technology, the Samsung S22 takes mobile excellence to a whole new level. Stay ahead of the curve and embrace the next generation of innovation with the Samsung S22.",
                            ProductName = "Samsung S22: Next-Gen Innovation"
                        },
                        new
                        {
                            ArticleNumber = "T-44183",
                            ImageUrl = "pexels-Lamp.jpg",
                            Ingress = " Elevate your space with our Large Ceiling Lamp featuring a captivating beige straw-like texture. This stunning fixture combines style and sophistication, adding a touch of natural elegance to any room. With its expansive size and unique texture, this ceiling lamp becomes a focal point, enhancing the overall aesthetic of your space. Experience the charm of our Beige Straw-Like Texture: Large Ceiling Lamp and illuminate your surroundings with exquisite beauty.",
                            ProductName = "Straw-Like Ceiling Lamp"
                        },
                        new
                        {
                            ArticleNumber = "DE-15963",
                            ImageUrl = "pexels-mirror.jpg",
                            Ingress = "Introduce a touch of contemporary elegance with our Round Mirror. This sleek and stylish mirror enhances the aesthetic of any space with its perfectly rounded shape. Its smooth edges and minimalist design create a modern and sophisticated look, making it a versatile addition to any room. Hang it on your wall to reflect light and open up your space, or use it as a chic decorative piece. Elevate your decor with the timeless appeal of our Round Mirror, adding a touch of elegance and functionality to your surroundings.",
                            ProductName = "Sleek and Stylish Mirror"
                        },
                        new
                        {
                            ArticleNumber = "SH-77124",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-shoes.jpg",
                            Ingress = "Elevate your footwear game with Nike Shoes. Combining style and performance, these shoes offer a perfect blend of fashion and function. From running to training, Nike Shoes provide unparalleled comfort and support for all your active pursuits. With a wide selection of designs and colors, you can find the perfect pair to express your personal style. Step into the world of Nike Shoes and experience the ultimate combination of style and performance.",
                            ProductName = "Nike Shoes"
                        },
                        new
                        {
                            ArticleNumber = "SH-89514",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-nikeshoe.jpg",
                            Ingress = "Elevate your footwear game with Nike Shoes. Combining style and performance, these shoes offer a perfect blend of fashion and function. From running to training, Nike Shoes provide unparalleled comfort and support for all your active pursuits. With a wide selection of designs and colors, you can find the perfect pair to express your personal style. Step into the world of Nike Shoes and experience the ultimate combination of style and performance.",
                            ProductName = "Nike Shoes: Style and Performance"
                        },
                        new
                        {
                            ArticleNumber = "SH-96315",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-whiteshoes.jpg",
                            Ingress = "Experience pure performance with our White Running Shoe. This sleek and stylish shoe is designed to enhance your running experience with its optimal comfort and support. The crisp white color adds a touch of timeless elegance to your athletic ensemble. Whether you're sprinting on the track or hitting the trails, our White Running Shoe delivers the perfect combination of functionality and style. Step up your running game with pure confidence in our White Running Shoe.",
                            ProductName = "White Running Shoe"
                        },
                        new
                        {
                            ArticleNumber = "LA-12856",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-tablelamp.jpg",
                            Ingress = " Illuminate your space with our sleek and stylish Black Table Lamp. This elegant lamp combines contemporary design with functional lighting, making it a perfect addition to any room. The sleek black finish adds a touch of sophistication, while the clean lines and minimalist aesthetic create a modern and chic look. Whether placed on a desk, nightstand, or side table, this black table lamp effortlessly enhances the ambiance of your space.",
                            ProductName = "Stylish Black Table Lamp"
                        },
                        new
                        {
                            ArticleNumber = "DR-22896",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-yellowdress.jpg",
                            Ingress = "This delightful dress radiates joy and positivity, perfect for brightening up any occasion. The vibrant yellow hue captures the essence of sunny days, while the lightweight and flowy fabric ensure comfort and ease. Whether you're strolling on the beach or attending a summer gathering, this dress is sure to turn heads and spread cheer. Experience the happiness of summer with our Sunshine Delight: Happy Yellow Summer Dress and let your style shine.",
                            ProductName = "Sunshine Summer Dress"
                        },
                        new
                        {
                            ArticleNumber = "DR-45875",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-whitedress.jpg",
                            Ingress = "This elegant and timeless piece exudes pure elegance, perfect for warm-weather occasions. The crisp white color adds a touch of sophistication, while the lightweight fabric keeps you cool and comfortable. Whether you're attending a beach party or enjoying a picnic in the park, our White Summer Dress is a must-have for effortless style. Step into summer with pure elegance in our White Summer Dress.",
                            ProductName = "White Summer Dress"
                        },
                        new
                        {
                            ArticleNumber = "IN-85875",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-tableandchairs.jpg",
                            Ingress = "Enhance your dining area with our Modern Dining Set featuring a sleek white tabletop and sturdy wooden legs. This contemporary design effortlessly combines style and functionality, creating a chic and inviting space for gatherings. With six chairs included, this dining set offers ample seating for family and friends. Experience the perfect blend of modern aesthetics and timeless charm with our Modern Dining Set: White Top, Wooden Legs.",
                            ProductName = "Modern Dining Set: Table with 6 chairs"
                        },
                        new
                        {
                            ArticleNumber = "SH-99875",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum mattis ante, eu cursus turpis volutpat vitae. Nullam consectetur pellentesque nibh, eu aliquet mauris bibendum in. Phasellus id diam nisl. Mauris sollicitudin, tortor sed rutrum tincidunt, turpis ligula pellentesque lorem, eu pulvinar mauris purus eu nisl. Sed non enim felis. Nullam non varius ipsum. Aliquam at tristique ex. Pellentesque pulvinar finibus tristique. Morbi a dui id lorem tincidunt aliquam ac vel erat.",
                            ImageUrl = "pexels-summer.jpg",
                            Ingress = "Step into summer style with our Blue Beach Slippers. These essential footwear options are perfect for your beach excursions. The vibrant blue color adds a pop of freshness, while the comfortable design ensures a relaxed and enjoyable experience. Whether you're walking along sandy shores or lounging by the water, our Blue Beach Slippers are the perfect companion for your beach adventures. Embrace the summer vibes with our must-have Blue Beach Slippers.",
                            ProductName = "Blue Beach Slippers: Summer Essentials"
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductArticleNumber");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b5e1f16-5c18-4f76-8f13-34e4055cfc99"),
                            Comment = "The Apple Watch Series 6 is a game-changer! The blood oxygen level monitoring, ECG feature, and always-on display are amazing. It seamlessly integrates with my iPhone and keeps me connected throughout the day.\" \n - Sarah",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3284),
                            ProductArticleNumber = "GC-58966",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("e826087d-9f5a-4dab-a1c2-97d8de8a04e2"),
                            Comment = "The Apple Watch Series 6 is a fantastic smartwatch. The larger display, faster performance, and improved heart rate monitoring are remarkable. It looks stylish, and the battery life easily gets me through the day.\" \n - Mark",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3310),
                            ProductArticleNumber = "GC-58966",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("76b369f8-7c02-47ca-9d7b-61f983b8f5e5"),
                            Comment = "I love my Apple Watch Series 6! The always-on display is a game-changer, and the ECG function gives me peace of mind. The build quality and design are top-notch. It's become an indispensable part of my daily routine.\" \n - Emily",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3314),
                            ProductArticleNumber = "GC-58966",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("c5af6803-4e94-4e0e-b7a2-1be02f77920e"),
                            Comment = "The Apple Watch Series 6 is a fantastic smartwatch. The larger display, faster performance, and improved heart rate monitoring are remarkable. It looks stylish, and the battery life easily gets me through the day.\" \n - Jason",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3317),
                            ProductArticleNumber = "FE-23456",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("9d352e0b-8ad0-4767-98cb-b87f871f7380"),
                            Comment = "The Apple Watch Collection is a game-changer! The sleek design and premium materials make it a stylish accessory that complements any outfit. The functionality is outstanding, with a wide range of features like heart rate monitoring, activity tracking, and notifications. The watch face is customizable, allowing me to personalize it to my liking. The battery life is impressive, lasting me through a full day of use. Overall, I highly recommend the Apple Watch Collection to anyone looking for a versatile and reliable smartwatch.\n - Michelle",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3320),
                            ProductArticleNumber = "FE-23456",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("f7a2b4c9-5f96-4be0-8768-8029a2dbbdd2"),
                            Comment = "The Apple Watch Collection offers an excellent blend of style and functionality. The variety of watch faces and interchangeable bands allow me to customize it to suit my preferences and occasions. The integration with my iPhone is seamless, enabling me to receive notifications, answer calls, and even use Siri directly from my wrist. The watch's performance is snappy, and the display is vibrant and easy to read. However, I would appreciate more third-party app support and improved battery life for longer usage without frequent charging. Overall, the Apple Watch Collection is a solid smartwatch choice for Apple ecosystem users. \n - Jim",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3323),
                            ProductArticleNumber = "FE-34567",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("13e21e76-bff3-4e20-a2b8-13e8c6c452b3"),
                            Comment = "The Apple Watch Collection is a game-changer! The sleek design and premium materials make it a stylish accessory that complements any outfit. The functionality is outstanding, with a wide range of features like heart rate monitoring, activity tracking, and notifications. The watch face is customizable, allowing me to personalize it to my liking. The battery life is impressive, lasting me through a full day of use. Overall, I highly recommend the Apple Watch Collection to anyone looking for a versatile and reliable smartwatch.\n - Linn",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3326),
                            ProductArticleNumber = "FE-34567",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("8eaa720c-1d2b-42cc-b8b9-11de0b37c708"),
                            Comment = "The Apple Watch Collection is a fantastic fitness companion. The built-in workout tracking features are accurate and comprehensive, helping me monitor my progress and set new fitness goals. The watch's heart rate monitor is incredibly useful during workouts, ensuring that I stay in my target heart rate zone. The GPS functionality allows me to track my outdoor runs accurately. The only downside is that the battery life could be better, especially during extended workouts. Nonetheless, I consider the Apple Watch Collection an essential tool for fitness enthusiasts.\n - Leah",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3330),
                            ProductArticleNumber = "FE-34567",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("d00f5cbf-ded4-4aa9-b19a-6363de249c85"),
                            Comment = "Love this dress! The yellow color is vibrant and perfect for summer. It's comfortable and flattering with a fun touch. Received lots of compliments. Highly recommended! - Leah",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3337),
                            ProductArticleNumber = "DR-22896",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("a6373522-648a-4cbb-b6ea-4a5fba0ae001"),
                            Comment = "Stunning white dress! Elegant, versatile, and comfortable. Perfect for any occasion. Highly recommended! - Linn",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3339),
                            ProductArticleNumber = "DR-45875",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("63885324-214a-4a41-a8d9-209209a303e2"),
                            Comment = "This backpack is a reliable companion! It provides sufficient storage for all my essentials, and its sturdy construction ensures durability. While I found the design to be simple, it serves its purpose well. - Tim",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3343),
                            ProductArticleNumber = "B-67898",
                            Rating = 3
                        },
                        new
                        {
                            Id = new Guid("0f7e5a7c-2e8b-4d7e-9b4a-f3f1eae8435a"),
                            Comment = "This backpack is a must-have! It offers ample storage space, durability, and a stylish design that suits any adventure",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3346),
                            ProductArticleNumber = "B-45678",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("48dc2404-39d3-4d9a-ae22-18c01c871e18"),
                            Comment = "This table lamp is a true gem! Its modern design and soft glow create a cozy ambiance in any room. The quality craftsmanship is evident, and it adds a stylish touch to my decor. - Laura",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3348),
                            ProductArticleNumber = "LA-12856",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("b45fc2df-853c-4d53-8ef0-ade4a64b536e"),
                            Comment = "These shoes are amazing! Comfortable, stylish, and perfect for any occasion. Highly recommended! - Jake",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3351),
                            ProductArticleNumber = "SH-77124",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("9aeeea0d-4f26-4167-8b3a-43236701feda"),
                            Comment = "These shoes exceeded my expectations! With their comfortable fit and stylish design, they're a great choice for any occasion. - Jim",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3375),
                            ProductArticleNumber = "SH-77124",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("d7e169c1-3f3f-4cb1-8975-942fa593f2d1"),
                            Comment = "I think this mirror is simply stunning! Its sleek design and impeccable craftsmanship add a touch of elegance to any space. - Laura",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3378),
                            ProductArticleNumber = "DE-15963",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("356b83b2-8a44-4e62-a1db-48f7a62e3518"),
                            Comment = "This running shoe is a game-changer! The cushioning and support provided are exceptional, making my runs comfortable and enjoyable. - Nicki",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3380),
                            ProductArticleNumber = "SH-96315",
                            Rating = 4
                        },
                        new
                        {
                            Id = new Guid("e853b69c-7a3e-4a97-9a4e-8157e9b44c47"),
                            Comment = "These shoes are amazing! Highly recommended! - Sara",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3382),
                            ProductArticleNumber = "BE-89214",
                            Rating = 5
                        },
                        new
                        {
                            Id = new Guid("9c49744f-7ef7-4c1e-9a46-6b81b19fc7c5"),
                            Comment = "These beach slippers are a summer essential! They offer a comfortable fit, great traction, and are perfect for sandy beaches and poolside lounging. I rate them 3/5 for their decent comfort and practicality. - Cindy",
                            Created = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(3384),
                            ProductArticleNumber = "SH-99875",
                            Rating = 3
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ProductId = "SH-99875",
                            TagId = 2
                        },
                        new
                        {
                            ProductId = "SH-99875",
                            TagId = 4
                        },
                        new
                        {
                            ProductId = "GC-58966",
                            TagId = 1
                        },
                        new
                        {
                            ProductId = "FE-23456",
                            TagId = 2
                        },
                        new
                        {
                            ProductId = "FE-23456",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "B-45678",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "B-67898",
                            TagId = 1
                        },
                        new
                        {
                            ProductId = "T-44183",
                            TagId = 1
                        },
                        new
                        {
                            ProductId = "DR-45875",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "LA-12856",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "IN-85875",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "SH-77124",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "DE-15963",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "L-96174",
                            TagId = 3
                        },
                        new
                        {
                            ProductId = "FE-12345",
                            TagId = 2
                        },
                        new
                        {
                            ProductId = "DE-52365",
                            TagId = 5
                        },
                        new
                        {
                            ProductId = "IN-89652",
                            TagId = 1
                        },
                        new
                        {
                            ProductId = "M-77124",
                            TagId = 1
                        },
                        new
                        {
                            ProductId = "BE-89214",
                            TagId = 2
                        },
                        new
                        {
                            ProductId = "IN-89652",
                            TagId = 2
                        },
                        new
                        {
                            ProductId = "DR-22896",
                            TagId = 2
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ShowcaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Showcases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 26, 11, 49, 30, 586, DateTimeKind.Local).AddTicks(2905),
                            ImageUrl = "pexels-goldchair.jpg",
                            Ingress = "WELCOME TO BMERKETO SHOP",
                            LinkText = "SHOP NOW",
                            LinkUrl = "/products",
                            Title = "Exclusive Chair gold Collection."
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.StockEntity", b =>
                {
                    b.Property<string>("ProductArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("money");

                    b.Property<bool>("OnSale")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StandardCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductArticleNumber");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductArticleNumber = "135685",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 0,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "356899",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 0,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "GC-58966",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 0,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "FE-12345",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 25,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "FE-23456",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 0,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "FE-34567",
                            Discount = 0.85m,
                            OnSale = true,
                            Price = 30m,
                            Quantity = 25,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "B-45678",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 50,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "B-67898",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 50,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "DE-52365",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 50,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "DE-45965",
                            Discount = 0m,
                            OnSale = false,
                            Price = 12m,
                            Quantity = 10,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "BE-75214",
                            Discount = 0m,
                            OnSale = false,
                            Price = 12m,
                            Quantity = 15,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "BE-89214",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "IN-89652",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "L-96174",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "M-77124",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 105,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "M-66124",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 105,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "T-44183",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 105,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "DE-15963",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "SH-77124",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "SH-89514",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "SH-96315",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "LA-12856",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "DR-45875",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "SH-99875",
                            Discount = 0.5m,
                            OnSale = true,
                            Price = 30m,
                            Quantity = 15,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "DR-22896",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        },
                        new
                        {
                            ProductArticleNumber = "IN-85875",
                            Discount = 0m,
                            OnSale = false,
                            Price = 30m,
                            Quantity = 125,
                            StandardCurrency = "USD"
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "new"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "popular"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "featured"
                        },
                        new
                        {
                            Id = 4,
                            TagName = "summer sale"
                        },
                        new
                        {
                            Id = 5,
                            TagName = "outgoing"
                        });
                });

            modelBuilder.Entity("WebbApp.Models.Entities.OrderRowEntity", b =>
                {
                    b.HasOne("WebbApp.Models.Entities.OrderEntity", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.HasOne("WebbApp.Models.Entities.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbApp.Models.Entities.ProductEntity", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductReviewEntity", b =>
                {
                    b.HasOne("WebbApp.Models.Entities.ProductEntity", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductArticleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductTagEntity", b =>
                {
                    b.HasOne("WebbApp.Models.Entities.CollectionEntity", "Collection")
                        .WithMany("ProductIds")
                        .HasForeignKey("CollectionId");

                    b.HasOne("WebbApp.Models.Entities.ProductEntity", "Product")
                        .WithMany("Tags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebbApp.Models.Entities.TagEntity", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.StockEntity", b =>
                {
                    b.HasOne("WebbApp.Models.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductArticleNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.CollectionEntity", b =>
                {
                    b.Navigation("ProductIds");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderRows");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Reviews");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("WebbApp.Models.Entities.TagEntity", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
